<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back</name>
   <tag></tag>
   <elementGuidId>dd248264-7fd9-481d-9eb6-4becbc42dae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/header/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.Link.Header-businessLink.Link--primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61413ff8-2477-4d05-aab2-4807a18cdfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Link Header-businessLink Link--primary</value>
      <webElementGuid>ec0f9a96-8695-464f-ba35-7c05587321d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://menu.neighborhood-restaurant.com/#/business/602def6f5824426788ef5461/a/cancel/KAN2023716-9caca</value>
      <webElementGuid>2479ec7d-9df4-4bc1-9350-29372090b34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Back to Mindboard Holdings LLC</value>
      <webElementGuid>13f9e3ff-4ce8-4b2b-95c0-03a257849ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mindboard Holdings LLC</value>
      <webElementGuid>cdc6c109-903c-4b20-b4d9-579f8bb44025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>e4da2a5f-22f9-440a-a381-cb19d9500be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>43ebf14f-a2ee-4bf8-a0aa-b022bab95a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App-Container is-noBackground flex-container justify-content-center&quot;]/div[@class=&quot;App App--singleItem&quot;]/div[@class=&quot;App-Overview&quot;]/header[@class=&quot;Header&quot;]/div[@class=&quot;Header-content flex-container justify-content-space-between align-items-stretch&quot;]/div[@class=&quot;Header-business flex-item width-grow flex-container align-items-center&quot;]/a[@class=&quot;Link Header-businessLink Link--primary&quot;]</value>
      <webElementGuid>bb59d63d-e160-4d24-a0f8-3401902d2d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/header/div/div/a</value>
      <webElementGuid>5fa12e4e-fb86-470e-8e18-37c8a3881223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Mode'])[1]/preceding::a[1]</value>
      <webElementGuid>f0670910-454a-40e3-a692-c8af750bfbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://menu.neighborhood-restaurant.com/#/business/602def6f5824426788ef5461/a/cancel/KAN2023716-9caca']</value>
      <webElementGuid>04d4c1f5-a96b-4d5f-90e3-c7f67ed5ca42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>1cdef38d-ffb1-42f0-9ece-b3cf326112b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://menu.neighborhood-restaurant.com/#/business/602def6f5824426788ef5461/a/cancel/KAN2023716-9caca' and @title = 'Mindboard Holdings LLC' and (text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>02c2be67-1c2a-45d8-ad6b-fe8d4d67e189</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
