<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ADD</name>
   <tag></tag>
   <elementGuidId>9ccb4376-acca-4594-8e3d-4947a1ef9dea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='29e34ca6-d7ed-4ebd-ab9f-7b1c9cdcf402']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1942a4ca-6370-454f-be10-7ad9ebd77525</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7769e80b-1933-425f-b9e0-d135e97b42b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-raised-button mat-button-base mat-focus-indicator w3-block menuAddButton menu-b ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>16a549ef-555f-4be4-b0bb-9cabcae07ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1942a4ca-6370-454f-be10-7ad9ebd77525</value>
      <webElementGuid>605a73e5-1c06-4beb-a25d-9db17b6e28e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ADD </value>
      <webElementGuid>a9781b40-53da-43f7-9eee-52fe23a3f028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1942a4ca-6370-454f-be10-7ad9ebd77525&quot;)</value>
      <webElementGuid>6665f1b8-5d30-41f0-ba46-02b92f51940b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='1942a4ca-6370-454f-be10-7ad9ebd77525']</value>
      <webElementGuid>a46f6ee1-d8ea-467c-94ce-2af02a1b0392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollto']/div[2]/div/div[3]/div/div[2]/div/div[2]/div[2]/div[2]/mat-card/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>4847bc05-0f22-4ef6-9637-4e92c15a37a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹15.95'])[1]/following::button[1]</value>
      <webElementGuid>4683f6f0-ca2c-42b8-98c4-e1e38536edd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD'])[1]/following::button[2]</value>
      <webElementGuid>351ed5c1-fca9-4f11-b0ad-ae6a5734475d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹19.95'])[1]/preceding::button[1]</value>
      <webElementGuid>f9ddc141-6623-4f53-b2f0-41c9a8329305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-card/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>b0c99ee5-e540-4ea9-8a65-734f4e554d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '1942a4ca-6370-454f-be10-7ad9ebd77525' and (text() = ' ADD ' or . = ' ADD ')]</value>
      <webElementGuid>42542a71-3106-4210-ae82-069630f324f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
