<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT</name>
   <tag></tag>
   <elementGuidId>0f7a2166-957e-4532-875b-b25746cf3c13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.w3-margin-left.w3-white.fw-700.oncheck.mat-stroked-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e03530aa-a94a-4f8f-96a7-3ecc1b7199b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da194ded-2d15-42fa-95d0-0f38f2093c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator w3-margin-left w3-white fw-700 oncheck mat-stroked-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>ddeece7f-f797-432c-9353-e72d0ac3dd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CHECKOUT </value>
      <webElementGuid>8275440b-9d52-4f06-ba2b-e59b07206bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollto&quot;)/div[@class=&quot;w3-padding footer hide_in_Mobile_only ipadPro ng-star-inserted&quot;]/div[@class=&quot;mtop-5&quot;]/div[@class=&quot;w3-row w3-margin-top w3-center ng-star-inserted&quot;]/button[@class=&quot;mat-focus-indicator w3-margin-left w3-white fw-700 oncheck mat-stroked-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>70d36930-2bc9-4252-9e90-0c6c1a73c4b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>986aa1cf-8b85-42ef-bbcc-0d5d52e09831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollto']/div[3]/div[5]/div[2]/button</value>
      <webElementGuid>5f1b65e2-8d5e-4a2b-9e26-10be8aeebdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹82.82'])[3]/following::button[1]</value>
      <webElementGuid>bb3abcf3-30cd-40d1-9612-3b561a900ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GRAND TOTAL :'])[1]/following::button[1]</value>
      <webElementGuid>c987cc61-defb-4eaa-9ebf-8688e97432e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breakfast'])[14]/preceding::button[1]</value>
      <webElementGuid>5b937a4f-e7a9-48ad-9de6-e3de850d0f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/button</value>
      <webElementGuid>63a2a410-1809-4c57-9c1c-38db61a4f23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' CHECKOUT ' or . = ' CHECKOUT ')]</value>
      <webElementGuid>d6320228-83bb-4dd8-99b2-468b447730e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
