<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_43.99</name>
   <tag></tag>
   <elementGuidId>5a8c663a-31ca-4173-9a75-cd280aa6e186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentToConvert']/div/div/div[3]/div[2]/div[6]/div[2]/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.w3-row.grandtotal > div.w3-col.s6.text-right > h4.m-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0cd827f0-0f25-45d1-aace-035a82890566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0</value>
      <webElementGuid>699f4597-f9ab-41c7-97ce-15070c73b0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>₹43.99</value>
      <webElementGuid>a5d29250-7bce-4873-bf3e-cf696a4dd95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentToConvert&quot;)/div[@class=&quot;allorders ng-star-inserted&quot;]/div[@class=&quot;detailwithorderNo&quot;]/div[@class=&quot;w3-padding&quot;]/div[@class=&quot;order-item w3-padding&quot;]/div[@class=&quot;w3-row grandtotal&quot;]/div[@class=&quot;w3-col s6 text-right&quot;]/h4[@class=&quot;m-0&quot;]</value>
      <webElementGuid>200b96c0-268e-47bf-85e0-ff70fbde34ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentToConvert']/div/div/div[3]/div[2]/div[6]/div[2]/h4</value>
      <webElementGuid>7fbccbe5-1f1f-48df-bbc2-50517e2572f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GRAND TOTAL'])[1]/following::h4[1]</value>
      <webElementGuid>9c22e501-34a2-4a4b-b677-9099c535e38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- ₹0.00'])[1]/following::h4[1]</value>
      <webElementGuid>b74c42c1-4e39-425c-80d5-4af6434dbb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Date &amp; Time'])[1]/preceding::h4[1]</value>
      <webElementGuid>f1fccec0-675c-4557-b78c-9ceb83d53d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='August 17, 2023 01:18'])[1]/preceding::h4[1]</value>
      <webElementGuid>1c0a4544-d65f-4138-ad32-540cfbeadd17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='₹43.99']/parent::*</value>
      <webElementGuid>037f7d83-1aa3-481e-b00e-c6deaf8d674a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/h4</value>
      <webElementGuid>68eeb275-9b7e-4605-9a33-d2d0deacddc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = '₹43.99' or . = '₹43.99')]</value>
      <webElementGuid>66ba772c-00aa-4b64-9c6a-4b8a1e3b4e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
