<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter 7 digit One Time Passwor_6a0b2d</name>
   <tag></tag>
   <elementGuidId>ab18bd1c-600a-4b86-b307-4c0d52bf2e11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'otp_4')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otp_2_hsgvcgay5atlldqx5p6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24a90871-ed73-4f21-b6ef-925a182f2980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8f2ed971-87e3-456a-939a-ec18f1100a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0289edc3-11a6-45bb-8d22-ad119b9405e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>3b4f8f57-b65e-4369-942e-27578ffc6e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp_2_hsgvcgay5atlldqx5p6</value>
      <webElementGuid>626cc6b6-931c-4988-97ea-5bded5af9ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bb0815f1-3f39-4daf-84de-33c6fe6cf7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57) || event.charCode == 0</value>
      <webElementGuid>9d4fd76c-16ff-4153-b0cc-d4f2d87fed3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>0e5b614d-f5dc-4a17-9657-720efe9aafdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp_2_hsgvcgay5atlldqx5p6&quot;)</value>
      <webElementGuid>7eae7f34-e913-48d8-8cff-f281aa923afa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp_2_hsgvcgay5atlldqx5p6']</value>
      <webElementGuid>308aa177-f7b1-45c4-a8c5-023d733b6f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c_hsgvcgay5atlldqx5p6']/input[3]</value>
      <webElementGuid>ee6a1344-fbf7-4460-b263-21026af3895e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>f19f66a7-10ed-4cb5-8ee4-2901df087c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp_2_hsgvcgay5atlldqx5p6' and @type = 'password']</value>
      <webElementGuid>77951224-9555-4bfa-b0b0-162b00e72bb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
