<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter 7 digit One Time Passwor_79bc49</name>
   <tag></tag>
   <elementGuidId>e078b593-ed56-4aaf-b334-793b8d3624d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'otp_5')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otp_6_hsgvcgay5atlldqx5p6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd017e2d-2973-4bd7-b225-0d93225788b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>54b74de7-8d6f-44d2-8e9a-16d2b543b5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>985f1020-0755-4aa7-bef9-7cd072388098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>d6dcac00-0ccb-4e1e-a28d-7593049e66e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp_6_hsgvcgay5atlldqx5p6</value>
      <webElementGuid>1da27ae7-db24-4281-b0a9-dd69b535e268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7d7b9b18-20e3-4849-95d6-24a3c90bf010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57) || event.charCode == 0</value>
      <webElementGuid>7480db72-a06b-4e0f-90db-4282f16f5d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>92498bdc-4fdf-4495-8c1c-996537a339a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp_6_hsgvcgay5atlldqx5p6&quot;)</value>
      <webElementGuid>4e7be0fc-a2c5-4340-89fd-6b014d51b08c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp_6_hsgvcgay5atlldqx5p6']</value>
      <webElementGuid>9262498d-7632-4e23-a5ce-b338107916d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c_hsgvcgay5atlldqx5p6']/input[7]</value>
      <webElementGuid>9389766d-7da6-4bec-890e-a582f492ee41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[7]</value>
      <webElementGuid>3447a37c-14dd-4d0c-bf32-f6193a85e756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp_6_hsgvcgay5atlldqx5p6' and @type = 'password']</value>
      <webElementGuid>e3397048-9316-48ab-abad-3136134252a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
