<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_indeterminate_check_box</name>
   <tag></tag>
   <elementGuidId>83bf1b81-e501-424d-9f36-e25cfc914ba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Veg Manchuria Bonus Hour X 1'])[1]/following::mat-icon[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.cartquantity.material-icons.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>d7631592-498b-4459-82eb-7d35525eba3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>08155b9a-0d27-49d7-bf05-ef1cab80e820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate cartquantity material-icons mat-icon-no-color</value>
      <webElementGuid>156e04cf-2c39-430e-bee3-9e30cb31daf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cabaf178-f1fe-4191-9189-0d1135667eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> indeterminate_check_box</value>
      <webElementGuid>aec75259-77e1-4b7c-88f0-db2c665e2f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-container&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content page-wrapper&quot;]/app-restaurant[@class=&quot;ng-star-inserted&quot;]/mat-drawer-container[@class=&quot;mat-drawer-container example-container mat-drawer-transition mat-drawer-container-has-open&quot;]/mat-drawer[@class=&quot;mat-drawer hide_in_Mobile_only ng-tns-c98-1 ng-trigger ng-trigger-transform ng-star-inserted mat-drawer-over mat-drawer-end mat-drawer-opened&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c98-1&quot;]/div[@class=&quot;category_Scroll3 ng-tns-c98-1&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;w3-padding hide_in_Mobile_only&quot;]/div[@class=&quot;inMobileCartSec w-100&quot;]/div[@class=&quot;w3-row&quot;]/div[@class=&quot;w3-col&quot;]/div[3]/div[@class=&quot;category_ScrollCartMenu&quot;]/div[@class=&quot;w3-row&quot;]/div[@class=&quot;w3-full&quot;]/div[@class=&quot;w3-row mb-4 ng-star-inserted&quot;]/div[@class=&quot;w3-row&quot;]/div[@class=&quot;w3-col w3-right&quot;]/div[@class=&quot;w3-row&quot;]/div[@class=&quot;w3-col w-50&quot;]/div[@class=&quot;w3-left pre-o-s&quot;]/mat-icon[@class=&quot;mat-icon notranslate cartquantity material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>9b498152-ffcc-4ed3-90d6-b01e1e2d65b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Veg Manchuria Bonus Hour X 1'])[1]/following::mat-icon[1]</value>
      <webElementGuid>084ace76-2188-4f5e-a077-1c40fbe7387c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUR CART'])[1]/following::mat-icon[1]</value>
      <webElementGuid>72045ff6-d623-460c-ba5d-28eaed45a460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹30.99'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>b130317c-9709-4e6d-bb81-0375860a7675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter menu instructions'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>9d1b8407-1270-4961-89f6-458fe087ebef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='indeterminate_check_box']/parent::*</value>
      <webElementGuid>072121d3-d9c5-4cd8-aa61-b818a145f187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/mat-icon</value>
      <webElementGuid>618f340b-1abe-4648-b1da-bf3cfe72d607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = ' indeterminate_check_box' or . = ' indeterminate_check_box')]</value>
      <webElementGuid>c43a39a3-e004-4bb2-a74b-a39af316b463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
