<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_coupon is not applicable ,please remove b_d44775</name>
   <tag></tag>
   <elementGuidId>0e0db78d-e8ce-4f79-ba16-dd832e7c3a96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-2']/app-bonushourcarterror/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.w3-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>28828ea1-a140-4635-a711-77473a820e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-center</value>
      <webElementGuid>8883380c-26b2-4ba7-bf0e-ddb57d9d0e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> coupon is not applicable ,please remove bonushourItem from your cart</value>
      <webElementGuid>cfc6cb6b-b428-4f18-a047-8c5ae9cbce70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-2&quot;)/app-bonushourcarterror[@class=&quot;ng-star-inserted&quot;]/p[@class=&quot;w3-center&quot;]</value>
      <webElementGuid>258e4134-d435-4e49-8ea8-74fb5643bf2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-2']/app-bonushourcarterror/p</value>
      <webElementGuid>d34c00a0-5d3b-4f25-b3a4-b0bfa144784d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹82.82'])[6]/following::p[1]</value>
      <webElementGuid>5cc044a5-d3c4-4174-815e-71487afe0480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::p[1]</value>
      <webElementGuid>b2c891bf-bc6e-48ad-9b2a-73193713f80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breakfast'])[14]/preceding::p[1]</value>
      <webElementGuid>87955663-9eef-49d5-9cb2-56dc4e41fa1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='coupon is not applicable ,please remove bonushourItem from your cart']/parent::*</value>
      <webElementGuid>ecb00db8-19dd-4899-ab12-24313c6a0b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-bonushourcarterror/p</value>
      <webElementGuid>dce34b4b-17e4-4cbb-b82a-f23a47cf4c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' coupon is not applicable ,please remove bonushourItem from your cart' or . = ' coupon is not applicable ,please remove bonushourItem from your cart')]</value>
      <webElementGuid>792f9871-efd0-4667-85c6-d6820dc72f25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
