<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back</name>
   <tag></tag>
   <elementGuidId>2e173bc8-9c06-41ef-9510-712943523f4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/header/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.Link.Header-businessLink.Link--primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd88562c-51f5-45d6-8c8a-d429c220306a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Link Header-businessLink Link--primary</value>
      <webElementGuid>df7ed5ae-a339-483e-9fd9-3eb3f69f9698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://menu.neighborhood-restaurant.com/#/business/602def6f5824426788ef5461/a/cancel/KAN2023716-b20b5</value>
      <webElementGuid>b5a69ffb-bc2c-4284-9680-b8fb2366a870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Back to Mindboard Holdings LLC</value>
      <webElementGuid>7b392f9f-85b4-419b-920c-0393b600ac37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mindboard Holdings LLC</value>
      <webElementGuid>75b74bc6-6c2a-475d-a28b-9b89809517f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>fb70c827-b13c-40d3-abef-7c2c49f66f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>be925df4-fa9f-4ae1-a2d0-aa96cf1cc6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App-Container is-noBackground flex-container justify-content-center&quot;]/div[@class=&quot;App App--singleItem&quot;]/div[@class=&quot;App-Overview&quot;]/header[@class=&quot;Header&quot;]/div[@class=&quot;Header-content flex-container justify-content-space-between align-items-stretch&quot;]/div[@class=&quot;Header-business flex-item width-grow flex-container align-items-center&quot;]/a[@class=&quot;Link Header-businessLink Link--primary&quot;]</value>
      <webElementGuid>98b12714-82ff-4eb2-b3ae-f4da69cb3010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/header/div/div/a</value>
      <webElementGuid>617fc2da-0d1e-4580-b61a-13b946ac47a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Mode'])[1]/preceding::a[1]</value>
      <webElementGuid>0564826f-65a2-4091-94e9-3f2a9d9a1123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://menu.neighborhood-restaurant.com/#/business/602def6f5824426788ef5461/a/cancel/KAN2023716-b20b5']</value>
      <webElementGuid>b69c1cd7-327e-478a-a83e-09b734e10f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>3b735a9c-0600-4597-b263-b34705a1cd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://menu.neighborhood-restaurant.com/#/business/602def6f5824426788ef5461/a/cancel/KAN2023716-b20b5' and @title = 'Mindboard Holdings LLC' and (text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>ddbac5c1-b297-4aa8-afe1-53faedfb0748</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
