<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card information_cardCvc</name>
   <tag></tag>
   <elementGuidId>dfdfad88-37dd-4700-a470-6d4b7c741e23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardCvc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cardCvc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a06c0ea0-5f5c-4523-af4d-28aec6d2c610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CheckoutInput CheckoutInput--tabularnums Input Input--empty</value>
      <webElementGuid>d3586c9e-0059-4560-8fbb-81bfc7fbf100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-csc</value>
      <webElementGuid>3011e4b9-bb3a-4d9a-83ba-c56d836874f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>53afc890-bf6c-4476-bf96-a689320f5511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eb285a0b-f381-4d8e-a5ab-b1e1d5c0102f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardCvc</value>
      <webElementGuid>f46db7d3-b7e3-419a-bb3e-3dff3ef4bb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardCvc</value>
      <webElementGuid>fd47ebd0-1005-4081-a0b5-593a43bff5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7493309d-fc49-4736-8fcc-18bd6b5376fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>ef7c22a0-4eef-443f-8a23-1a069a6bfc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>CVC</value>
      <webElementGuid>8f5687cd-85bb-4248-833c-69f50b0a94c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CVC</value>
      <webElementGuid>b43c33b7-c89d-4dc6-958f-3b8c19161bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4f7b4af5-ccb3-41ee-979d-6c58eee9f256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardCvc&quot;)</value>
      <webElementGuid>056a8785-0566-4eeb-bde7-454c8f3d2fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardCvc']</value>
      <webElementGuid>ad6063a9-9c14-4785-b6d9-7c20943c5b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cardNumber-fieldset-inner']/div[3]/div/div/span/input</value>
      <webElementGuid>9e7d7b68-86c8-460e-87f1-7c58278d47f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/input</value>
      <webElementGuid>29219140-2a01-4dd8-aced-932b5fb08015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cardCvc' and @name = 'cardCvc' and @type = 'text' and @placeholder = 'CVC']</value>
      <webElementGuid>ed22c75c-56da-4f7b-b005-813f7dc0a1bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
