<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_done_outline</name>
   <tag></tag>
   <elementGuidId>14ee74bd-f6b2-4a0c-861a-ac84d0206479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[17]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.w3-center.mat-flat-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ccd86a12-89cd-4e40-a39f-b9cdcfd2e69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6d5d985-7974-43e7-970c-d7b170fd8622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator w3-center mat-flat-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>74d92e9b-b997-4707-b1dc-fd0e9aad7030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>done_outline</value>
      <webElementGuid>18b9faa2-2475-4bdf-b967-f0ffe4cfc287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-2&quot;)/app-tip[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;w3-row w3-center w3-margin-top&quot;]/button[@class=&quot;mat-focus-indicator w3-center mat-flat-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>ef36d22f-7797-4c66-8599-3baa9cdad3c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[17]</value>
      <webElementGuid>a9efdbcb-6215-489c-b6f5-ee5d5665b3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-2']/app-tip/div[4]/button</value>
      <webElementGuid>9318d4dc-67a6-4ce0-bdf7-aa292174bbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter tip amount'])[1]/following::button[1]</value>
      <webElementGuid>fd8361e1-9a81-49f9-bd4f-ea1841073e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Amount'])[1]/following::button[1]</value>
      <webElementGuid>42012423-bcf9-42f8-a927-02e218ec54e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breakfast'])[14]/preceding::button[1]</value>
      <webElementGuid>50287a94-6f93-4d89-82ae-417484284a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon'])[17]/preceding::button[1]</value>
      <webElementGuid>0365d3df-e83b-4f3f-b793-1b66eb81e0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-tip/div[4]/button</value>
      <webElementGuid>298b3e67-b4df-4ec4-aab4-4a9177295fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'done_outline' or . = 'done_outline')]</value>
      <webElementGuid>5f217f64-383a-41fd-8c5a-4bddc1c334c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
