<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter 7 digit One Time Passwor_0e407f</name>
   <tag></tag>
   <elementGuidId>2adb7415-461d-4917-9ead-3c422ac400ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'otp_1')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otp_3_xlsodjkzh9klld2o8tv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa6c0242-e70d-4dec-94c6-e872af9bea76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2e2374e4-a59a-417f-8144-ab1e39170c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b76e9cd1-8699-4726-b2e8-4f484a1bd332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>3a6f8ab9-e098-4c50-8246-e08ade33e9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp_3_xlsodjkzh9klld2o8tv</value>
      <webElementGuid>3f028d5e-8cd3-4c07-b2c6-2b7cdf2dd508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b093eafc-8fa3-4036-a157-f02bcf4c71c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57) || event.charCode == 0</value>
      <webElementGuid>9228c950-52fd-4271-b699-137c7fc6aa67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>7c4b944e-ddb8-4044-a6cb-62c326a7e8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp_3_xlsodjkzh9klld2o8tv&quot;)</value>
      <webElementGuid>56f73c7f-643b-4234-814a-fbd08c33929a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp_3_xlsodjkzh9klld2o8tv']</value>
      <webElementGuid>ce33f5a1-5d83-4038-bc0d-f5c103ad8081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c_xlsodjkzh9klld2o8tv']/input[4]</value>
      <webElementGuid>06b46398-5538-4ff4-a8ab-fe4cbf721aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>a118c78a-000f-4104-8c1b-059f513d72fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp_3_xlsodjkzh9klld2o8tv' and @type = 'password']</value>
      <webElementGuid>20835869-a04d-4cd9-8a01-0564b48eeabf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
