<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back</name>
   <tag></tag>
   <elementGuidId>22ecea3b-6a4d-4f22-aa8c-78914e09963a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/header/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.Link.Header-businessLink.Link--primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5cc2da0a-5dab-4fea-9ff7-297d052c5cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Link Header-businessLink Link--primary</value>
      <webElementGuid>2e49ca66-7656-44fa-8f1f-473c671527b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://menu.neighborhood-restaurant.com/#/business/602def6f5824426788ef5461/a/cancel/KAN2023716-ca58f</value>
      <webElementGuid>74028fb6-d6b2-491f-a54f-bcc595bb9a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Back to Mindboard Holdings LLC</value>
      <webElementGuid>12ac4ded-448b-4acd-89e2-7d0d6823c17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mindboard Holdings LLC</value>
      <webElementGuid>cdea28ce-83bd-4c75-bb7d-6e90ba8c5662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>f5bae968-a05c-4d0e-b542-044589707e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>8dc19e62-589d-47b8-82ce-240906a867e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App-Container is-noBackground flex-container justify-content-center&quot;]/div[@class=&quot;App App--singleItem&quot;]/div[@class=&quot;App-Overview&quot;]/header[@class=&quot;Header&quot;]/div[@class=&quot;Header-content flex-container justify-content-space-between align-items-stretch&quot;]/div[@class=&quot;Header-business flex-item width-grow flex-container align-items-center&quot;]/a[@class=&quot;Link Header-businessLink Link--primary&quot;]</value>
      <webElementGuid>4b0f9549-e4be-4f39-a473-528b25e513ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/header/div/div/a</value>
      <webElementGuid>de9e335b-042f-4ac1-9ff3-af17a282bb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Mode'])[1]/preceding::a[1]</value>
      <webElementGuid>ae2fbc5c-31db-41c2-aa69-e3011d90986f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://menu.neighborhood-restaurant.com/#/business/602def6f5824426788ef5461/a/cancel/KAN2023716-ca58f']</value>
      <webElementGuid>ffe1a726-fdeb-43aa-a51d-046568895bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>f268408c-e093-487b-9665-c17eee6f1b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://menu.neighborhood-restaurant.com/#/business/602def6f5824426788ef5461/a/cancel/KAN2023716-ca58f' and @title = 'Mindboard Holdings LLC' and (text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>ac45bab1-bead-4f35-b0ce-11d73bee64da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
