<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Review Cart shopping_cart (2)</name>
   <tag></tag>
   <elementGuidId>4f88d837-8677-472c-ac76-f10c84d8b38a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollto']/div[2]/div/div[3]/div/div/div/div[4]/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.w3-text-white.inMobileFilterBtn.mat-stroked-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ecea25e-7ad3-4eba-b12d-d5845dbf29f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator w3-text-white inMobileFilterBtn mat-stroked-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>e9a4b029-2d32-4cb1-bb6f-e6d946eec6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Review Cart shopping_cart (2) </value>
      <webElementGuid>07537351-d195-4dff-927e-010c242b07ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollto&quot;)/div[@class=&quot;w3-container w-100 ng-star-inserted&quot;]/div[@class=&quot;inMobile_MenuTitle ng-star-inserted&quot;]/div[@class=&quot;inMobile_MenuTitle tempalte2 ng-star-inserted&quot;]/div[@class=&quot;menu_Scroll1 cartDivHeightTemplate2 show&quot;]/div[@class=&quot;MenuIteamsTop&quot;]/div[1]/div[@class=&quot;w3-row hide_in_Mobile_only&quot;]/div[@class=&quot;w3-full w3-container&quot;]/div[@class=&quot;selcMenu inMobile_Filter hide_in_Mobile_only ng-star-inserted&quot;]/button[@class=&quot;mat-focus-indicator w3-text-white inMobileFilterBtn mat-stroked-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>f4491489-b0fd-459c-9a32-3d770b58b682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollto']/div[2]/div/div[3]/div/div/div/div[4]/div/div/button</value>
      <webElementGuid>c0bef9e7-3a38-4581-99b9-8131cfcfab91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLEAR'])[2]/following::button[1]</value>
      <webElementGuid>7f41f4ce-0b47-4f7f-b262-ed9d55c8307d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[2]</value>
      <webElementGuid>d5618d96-3e33-43b0-a3ba-246a22fdc98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BONUS HOUR'])[1]/preceding::button[2]</value>
      <webElementGuid>f779a2e3-1de3-436a-81e2-4c0dea9005c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>4d8bdb83-aedd-4e6e-b5dc-8c808ca8e40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Review Cart shopping_cart (2) ' or . = ' Review Cart shopping_cart (2) ')]</value>
      <webElementGuid>58187215-54ac-45ad-9663-b33a94e577e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
