<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select Coupon</name>
   <tag></tag>
   <elementGuidId>0f3b6688-f4ee-4c3f-8a84-b732c3c5dda6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='60c9a1f25ecb8efabb8ba6f4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#60c9a1f25ecb8efabb8ba6f4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e605f1f9-83eb-4d2d-8a41-2a5757560d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-green selectedButton</value>
      <webElementGuid>46e8bf0d-3f6a-4749-bb1a-39bb4c607e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>60c9a1f25ecb8efabb8ba6f4</value>
      <webElementGuid>0b0df030-1833-45c9-8d75-418db5ae5283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Coupon </value>
      <webElementGuid>0200c51d-2951-4b96-a230-bc50ca11cf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;60c9a1f25ecb8efabb8ba6f4&quot;)</value>
      <webElementGuid>4ae4b691-5c51-4789-adcd-47a80aa38082</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='60c9a1f25ecb8efabb8ba6f4']</value>
      <webElementGuid>4a66dedd-c2c5-4299-a051-b90027a7acb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-coupon/div/div[2]/div[2]/mat-card/div/div/div/div[4]/div/button</value>
      <webElementGuid>aa715d0f-cae6-45bc-bc24-f5831f6dbdbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganesh_001'])[1]/following::button[1]</value>
      <webElementGuid>6b0b33fc-45bd-41c1-8601-2a784b67805b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::button[1]</value>
      <webElementGuid>505954e6-ce0a-4591-957c-413927b4a09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganesh_002'])[1]/preceding::button[1]</value>
      <webElementGuid>2b0b81b7-7593-4c1f-bf8f-6b0ce51d5fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Coupon'])[3]/preceding::button[1]</value>
      <webElementGuid>85066782-ddfb-4865-b362-fed65bae802d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>6cc2743a-ada4-4a8d-925d-7056a680ac04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '60c9a1f25ecb8efabb8ba6f4' and (text() = 'Select Coupon ' or . = 'Select Coupon ')]</value>
      <webElementGuid>759d7806-f7c7-432d-a48a-1b7023017957</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
