<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter 7 digit One Time Passwor_9125c2</name>
   <tag></tag>
   <elementGuidId>e85400e7-c6d9-4b6a-86d8-2d16692a545b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'otp_3')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otp_6_tn39x6af1jlldjuimo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83bd2330-884d-477b-ad5f-42a17d7fc7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c46f7c7f-9f05-4c9d-8b16-ddf77e16ce6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a91897d2-bbb1-431e-88f4-44abaca6b448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>736d718d-37bc-4871-b900-b6e45e5668a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp_6_tn39x6af1jlldjuimo</value>
      <webElementGuid>055282ab-d1e5-42ab-ba2d-d4151f21280f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0e5f7439-b244-4869-946e-026e92ab5f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57) || event.charCode == 0</value>
      <webElementGuid>c59e0712-0911-49c3-9ede-6f44e3993c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>98040130-3378-4f0c-adbb-3b61a856252a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp_6_tn39x6af1jlldjuimo&quot;)</value>
      <webElementGuid>8b39f226-2ba0-4da6-9bd8-b8d2bb51a8e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp_6_tn39x6af1jlldjuimo']</value>
      <webElementGuid>7a7955e6-8383-4eeb-98f2-766fb8be8059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c_tn39x6af1jlldjuimo']/input[7]</value>
      <webElementGuid>47f2382c-8c78-453b-8af7-017bbb478143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[7]</value>
      <webElementGuid>3fe7936f-0da7-4c13-bac2-3fbeefb6d96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp_6_tn39x6af1jlldjuimo' and @type = 'password']</value>
      <webElementGuid>42edb924-5174-4df8-aab2-eab150721f1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
