<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_coupon is not applicab_78ffa5</name>
   <tag></tag>
   <elementGuidId>3935ad2e-b7c3-4137-bc8a-3a38c3bf7e07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-2']/app-bonushourcarterror/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'mat-dialog-2' and (text() = ' coupon is not applicable ,please remove bonushourItem from your cartOk' or . = ' coupon is not applicable ,please remove bonushourItem from your cartOk')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>36db6cfc-5c32-4bba-8415-7604106f48d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>94c75a80-00b8-404f-bbd2-7c2f8d4429b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f709cbdc-70d3-45a5-a960-bb350352d206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c60-20 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>786fd699-1b8b-49ec-82b8-adaf5999a31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-2</value>
      <webElementGuid>fa28511c-911a-4844-8b58-7a973312f49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>6c1281c5-6eca-4fab-9200-ff37374f1340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> coupon is not applicable ,please remove bonushourItem from your cartOk</value>
      <webElementGuid>2fd1ec29-3b5b-4639-b893-8d9972295537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-2&quot;)</value>
      <webElementGuid>3ef6cbd0-9b2d-4a47-af2e-6a3dac4c420d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-2']</value>
      <webElementGuid>9a60a4d8-bdcb-4c03-a9e1-b9dc3ee3144c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-6']/mat-dialog-container</value>
      <webElementGuid>43f39452-0f1a-4b6e-a772-49bb1f067bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-dialog-2', '&quot;', ')')])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>449a18f1-4896-4901-995a-305c7b78e6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breakfast'])[14]/preceding::mat-dialog-container[1]</value>
      <webElementGuid>732b8465-f51a-4e77-9660-1297f5dce152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>9b24000d-efe9-4971-93a8-231aba462025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-2' and (text() = ' coupon is not applicable ,please remove bonushourItem from your cartOk' or . = ' coupon is not applicable ,please remove bonushourItem from your cartOk')]</value>
      <webElementGuid>60fed91a-ad70-451c-b449-19333d5321cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
