<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ADD_1</name>
   <tag></tag>
   <elementGuidId>f55187a4-9d71-48a9-a8d2-7248a89de760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='76e2d217-fb9f-4324-863d-1946aa64d5a7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#76e2d217-fb9f-4324-863d-1946aa64d5a7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35911f86-c222-41cd-9358-e55a76d8cb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-raised-button mat-button-base mat-focus-indicator w3-block menuAddButton menu-b ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>24789ad9-6344-4544-b75a-58a0e937d793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>76e2d217-fb9f-4324-863d-1946aa64d5a7</value>
      <webElementGuid>0279d84b-c6f7-4082-a136-9560d05b0e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ADD </value>
      <webElementGuid>fc77fad7-6264-45ec-9821-8bc25ff747c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;76e2d217-fb9f-4324-863d-1946aa64d5a7&quot;)</value>
      <webElementGuid>1805f197-07c4-4b88-9bdc-a629b475a073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='76e2d217-fb9f-4324-863d-1946aa64d5a7']</value>
      <webElementGuid>94572bd0-0202-4178-be2e-97541071521c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollto']/div[2]/div/div[3]/div/div[2]/div/div[2]/div[2]/div[2]/mat-card/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>09343ac9-c397-4611-974e-e0744da0e720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹10.99'])[1]/following::button[1]</value>
      <webElementGuid>6f80083a-23b6-48d0-8fed-b90cba8e1fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD'])[12]/following::button[2]</value>
      <webElementGuid>20ca39d0-7245-4e95-af14-75c35fbe321d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹15.95'])[1]/preceding::button[1]</value>
      <webElementGuid>d4b6e498-f3a8-4bd9-9add-93ea9ddb292e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-card/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>73c9939a-491e-4124-9ff9-3ee9cc3cd608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '76e2d217-fb9f-4324-863d-1946aa64d5a7' and (text() = ' ADD ' or . = ' ADD ')]</value>
      <webElementGuid>a347ae4c-a6e2-457c-abd0-1194fe03eba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
