<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Review Cart shopping_cart (2)</name>
   <tag></tag>
   <elementGuidId>e3d7cd62-5baa-466c-8e29-e7614b2fb7f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollto']/div[2]/div/div[3]/div/div/div/div[4]/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.w3-text-white.inMobileFilterBtn.mat-stroked-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1efc5398-2746-4c71-ab01-34cd3db848b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator w3-text-white inMobileFilterBtn mat-stroked-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>6b239dc7-2aac-4b18-9bc1-ac69907d6f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Review Cart shopping_cart (2) </value>
      <webElementGuid>c7293b0a-3bd8-402a-8f5e-bd0ac1d2bfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollto&quot;)/div[@class=&quot;w3-container w-100 ng-star-inserted&quot;]/div[@class=&quot;inMobile_MenuTitle ng-star-inserted&quot;]/div[@class=&quot;inMobile_MenuTitle tempalte2 ng-star-inserted&quot;]/div[@class=&quot;menu_Scroll1 cartDivHeightTemplate2 show&quot;]/div[@class=&quot;MenuIteamsTop&quot;]/div[1]/div[@class=&quot;w3-row hide_in_Mobile_only&quot;]/div[@class=&quot;w3-full w3-container&quot;]/div[@class=&quot;selcMenu inMobile_Filter hide_in_Mobile_only ng-star-inserted&quot;]/button[@class=&quot;mat-focus-indicator w3-text-white inMobileFilterBtn mat-stroked-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>dbecdb75-64e0-41f2-8ffd-85646aee6628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollto']/div[2]/div/div[3]/div/div/div/div[4]/div/div/button</value>
      <webElementGuid>bc1a131f-da9d-4fa7-8644-82ce487383ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLEAR'])[2]/following::button[1]</value>
      <webElementGuid>d97baef1-deb9-498c-a5cf-5fc78e17d9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[2]</value>
      <webElementGuid>84d1b11b-b7a2-4395-aef6-fb8c610866f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BONUS HOUR'])[1]/preceding::button[2]</value>
      <webElementGuid>cebff351-c388-4179-9991-bac8edbe84fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>db875b35-10b4-478c-bb31-2827af6774c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Review Cart shopping_cart (2) ' or . = ' Review Cart shopping_cart (2) ')]</value>
      <webElementGuid>35c1335d-8cf8-442c-aa4c-199be5a85842</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
